### ISSUE TITLE
Model deployment

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/quests#15]
This is meant to be pretty general but let's take an underwriting model for a personal auto carrier as an example. The starting point is a trained u/w score model and decision rules on whether to accept/deny/defer to human an auto insurance application. We want to expose this model as a service so apps/websites can hit it.

This is impactful/important because we need to demystify the operationalization process, and data scientists (incl. actuaries) should be familiar with the entire stack even if their day-to-day isn't orchestrating containers.

Initial assumptions/requirements
- Couple flavors
  - Saved TF model with TF Serving
  - Native R model with plumber
- Ideally we'd have a solution that's cloud vendor independent
- Docker + k8s; this should be scalable to the top insurers
- Some basic CICD mechanism
- Some basic authentication

Results
- Code
- Blog post

**Comment by EKtheSage** [comment]
Do we need to include the python's deployment framework? My colleague at work likes to talk about how easy it is to use flask to deploy model. Personal;y I am fine either way, as long as we can integrate our model with the IT team smoothly. 

Blog posts about using docker and R to deploy models have been showing up more recently:

- Tmobile TF deployment with plumber: https://github.com/tmobile/r-tensorflow-api
- Telethon Kids Institute docker with HTTPS connection for SSL encryption: https://telethonkids.wordpress.com/2019/03/26/use-rstudio-server-in-a-virtual-environment-with-docker-in-minutes/
- Shinyproxy + RStudio Server: https://www.rkingdc.com/blog/2019/3/27/approximating-rstudio-server-pro-and-shiny-server-pro-and-jupyterhub-for-free
- Docker and R plumber with SSL: https://qunis.de/how-to-make-a-dockerized-plumber-api-secure-with-ssl-and-basic-authentication/

**Comment by kevinykuo** [comment]
Yeah we can include an example with flask, although there are probably fewer use cases where flask would be used (I can't think of a good example outside of serving pickled scikit-learn models.)

**Comment by kevinykuo** [comment]
https://quests.kasa.ai/model-deployment/
