### ISSUE TITLE
P&C pricing tutorial in R

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/quests#3]
There is quite a bit of information on P&C ratemaking available, e.g. the [Werner and Modlin text](https://www.casact.org/library/studynotes/Werner_Modlin_Ratemaking.pdf) and the [CAS monograph on GLM](https://www.casact.org/pubs/monographs/index.cfm?fa=goldburd-Khare-Tevet-monograph05); however, there doesn't seem to be a tutorial for doing a ratemaking project end-to-end with R. The goal of this proposed project is to produce a tutorial or series of blog posts that emulates what actuaries do (at least the technical bits) in a typical pricing project, from preparing raw data to filing.

This work will be conducted in a public GitHub repo and open to contributions throughout.

Currently recruiting
- Actuaries with practical experience in ratemaking

**Comment by bigalxyz** [comment]
Hi Kevin. Saw your reply on the other forum. How do I sign up? I’ve subscribed to receive notifications...is that the same thing? (I’m new to github)

Thx

**Comment by kevinykuo** [comment]
Repo is now set up at https://github.com/kasaai/pc-pricing-tutorial.

**Comment by genedan** [comment]
I'm interested

**Comment by kevinykuo** [comment]
@genedan Awesome!

**Comment by kevinykuo** [comment]
Closing since we have enough to get started. If anyone else comes across this, we're always open to contributions.
