### ISSUE TITLE
workers compensation rating

### ISSUE THREAD

**Issue by ryanbthomas** [kasaai/quests#9]
Workers Comp Rating Plans vary by state. Many states use the NCCI rating plan, but others have their own bespoke plans. They all share some common features. My proposal is the to create a unified R interface to these rating plans so that actuaries can 

- have an easy way to re-rate portfolios of policies given updated rating plan.
- have an independent way to validate the implementation of the rating plan in there company's systems.

I started to collect information to do this several years ago, but I didn't get very far: [wcratr](https://github.com/actuarialvoodoo/wcratr/issues)

**Comment by kevinykuo** [comment]
This is interesting. If there's enough similarity in these processes (either among WC carriers within a state or among all states that use NCCI) maybe we can have standardized reports (think Rmd templates) that can be generated given data that's been normalized to some specs. I don't have experience with WC rating to comment further though.

@joezfang you got any thoughts on @actuarialvoodoo's proposal?

Also, noob question, what outputs from the NCCI are public vs. proprietary (i.e. available to member insurers only)? There seems to be quite detailed info from skimming through the filings. Would a public API of some sort make sense?

**Comment by joezfang** [comment]
I think this is definitely an interesting idea! From my experience the processes among NCCI states are similar enough that standardized reports seem very achievable. I'm not too sure about non-NCCI states, but i can't imagine them being too different.

In terms of public vs proprietary, I believe that NCCI rate filings are available to the public once they have been approved by state regulators. Our rating manuals are only available to affiliates though (or non-affiliates behind a paywall).

**Comment by ryanbthomas** [comment]
An initial "easy" win might be to provide a unified API to calculate
experience mod. I believe all of the rating plans have them. The basic
inputs are the same. And it would be useful.

**Comment by kevinykuo** [comment]
Let's do this. Ideas on the package name? `wc`?

**Comment by ryanbthomas** [comment]
my orignal name was `wcratr`, but perhaps `wcrater` is more clear.

**Comment by ryanbthomas** [comment]
I think `wc` isn't specific enough. Also, I'm thinking about a package name -- obviously we can call the kasa.ai projection something more human readable.

**Comment by kevinykuo** [comment]
Let's go with `wcrater` if that's okay, I feel like `wcratr` is harder to parse. Wanna start a repo for it? You should have the permissions now.

**Comment by ryanbthomas** [comment]
yep. I'll do that and move the issues I filed in my original repo here.
